### ISSUE TITLE
Fluid pump!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [bdew-minecraft/pressure#26]
Yo dawg, where be da fluid pump at to empty gazillions of bukkits of lava underground to me home?

**Comment by bdew** [comment]
I might one at some point... There's like half a dozen other mods with one for now.

**Comment by Unrepentant-Atheist** [comment]
Yea, no, I ain't getting a mod just for one block :P. Nah, handpump will do...for now.

**Comment by mindforger** [comment]
i am working on a magic mod pack, searching for a mod like yours, adding "tools and stuff" without hightech machinery, but i did not find any alternative "pump" block.

currently i am creating lava with bloodmagic, pick and placing it to a nearby tank via a bucket to provide my base with lava where i need it and my tinkers smeltery. 

having a right click driven pump block would be awesome, as i have to do some magic before i can afford to automate it and for early game a less error prone solution againts a bucket ...

man i burned my self so often because i did not hit the tank on first klick attempt

**Comment by HeliosDK** [comment]
Any chance of making a reverse drain like the redpower pump system in the future?

**Comment by Utildayael** [comment]
Given the theme of the pack, I could see this actually fitting in well. I mean, it is fluids and fluid transfer related... :)

You're absolutely right tho, there's a ton of options out there to do this and even output _into_ PP for transport.

Off the top of my head and definitely not all-inclusive...
- IndustrialCraft
- Mekanism
- Immersive Engineering
- Magneticraft
- BuildCraft
- Tom's Mod
- RotaryCraft

Over half of these exist for 1.10 currently...

Of course the con against PP adding a pump like this would be that bdew has no power system in this mod and adding a "power free" pump could be considered super cheaty. He'd have to add in a power req which adds in bulk to the pack as nothing else requires power, blah blah blah.

Would be nice from a "I want to use PP for everything" standpoint but I can see both sides.

**Comment by Tachrayonic** [comment]
I agree that pumping liquids into the system is something that should use power, and since this mod does not use power it's probably not a good idea to implement it for the sake of having this feature. One option could be to make an un-powered pump that only pulls liquids from above, like a drain.

As for putting liquids back into the world, this really doesn't need power, and I can really see this fitting really well. This would work like a combination of the Fluid Drain and Buildcraft's Flood Gate, filling in the area in front of the block, and any connecting blocks at an equal or lower elevation, probably with some sort of range limit for performance or chunk-related reasons.
(Just a thought: Both these mechanics should consider 'lighter than air' liquids/gasses, and drain/pour in an upside-down direction)

As for the other mods which can push liquids back into the world on a large scale, I don't think one currently exists for 1.10. I looked at all the mods on Utildayael's list and none of them both have this mechanic and have been updated to 1.10. If you know of any, please let me know.

**Comment by Utildayael** [comment]
Push fluid blocks into world? There's only two I know of for 1.10 and I didn't list one as it wasn't really a pipe system. 

Pressure Pipes obviously. :)

The other one is Actually Additions which has a fluid placer which works just like the PP sluice.

**Comment by Tachrayonic** [comment]
Placing a single block of liquid into the world is easy, you can even do some liquids with the vanilla dispenser. What I'm looking for is one that does it on a large scale, to pump a tank's worth of liquid out to create a lake. As far as I've looked, there is no mod for 1.10 that has that large scale pumping to world yet.

---

Push fluid blocks into world? There's only two I know of for 1.10 and I didn't list one as it wasn't really a pipe system.

Pressure Pipes obviously. :)

The other one is Actually Additions which has a fluid placer which works just like the PP sluice.

**Comment by mindforger** [comment]
something like the BC Flood Gate ?

**Comment by Tachrayonic** [comment]
Yes, exactly. A way to fill a volume of space with a liquid.

---

something like the BC Flood Gate ?

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
