### ISSUE TITLE
Fluid intakes/outlets on tanks causing increased rate of chunk updates

### ISSUE THREAD

**Issue by Caldurin** [bdew-minecraft/pressure#34]
Hi there. Whilst experimenting with your mods, I noticed that pressure pipes tanks were causing the number of chunk updates to increase considerably. Testing on a superflat world, I noticed a spike in chunk updates when fluids are flowing into or out of the tanks. 
Tank fluid intakes, tank fluid outlets and powered tank fluid outlets all seem to cause the same increase in chunk updates, but I can't reproduce the issue when using the pressurised intakes/outlets.
My test tanks were all contained within single chunks, in case there were chunk boundary issues.

I can't rule out there being any cross-mod interaction, as I have a lot of other mods loaded, but I haven't noticed any similar issues when testing with railcraft tanks. I'm also not experiencing any problems with intakes/outlets in advanced generators machines - it seems confined to the pressure pipes tanks.

**Comment by bdew** [comment]
How are you measuring it? Just F3 or some mod?

It's odd that you see more updates with intakes/outlets because they don't do anything special. The tank controller sends an update every time the fluid ammount changes and triggers a rendering update  on indicators. That can do up to 1 chunk update per tank controller per tick.

Are you sure it's not whatever pipes you are connecting to the outlets/intakes? Also how many updates are we tanking here?

**Comment by Caldurin** [comment]
I'm just using the f3 debug menu. The test setup with the single tank in an empty superflat world was going from 0-2 chunk updates per second when idle, to around 20 with fluids flowing in.
The test setup where I initially noticed this behaviour had several tanks in use and I was seeing much higher numbers, in the range of 100 chunk updates per second. However I went and broke all the machines trying to find the cause, so I can't reproduce those numbers, unfortunately

Having done a little more testing, it appears to be only related to pipes that "flow", such as the thermal dynamics fluiducts and ender io basic fluid conduits. The ender conduits that teleport fluids aren't showing an increase in chunk updates. Extra utilities transfer pipes only seem to cause an increase when using a large number of speed upgrades in them, so I guess it's consistent with frequent fluid updates triggering rendering updates.

.

**Comment by bdew** [comment]
I've done some testing as well and noticed a few things:
- Tank Controllers that have fluids flowing in/out will produce up to 20 updates per second
  - This is required for indicators to work but for now happens even if no indicators present
  - I'll look into preventing them if the tank has no indicators
- Tank Indicators in different chunks than controllers will add up to 20 per chunk per second as well
  - This is required for them to render the fluid level
  - Those updates are clientside with no increased network load
- In some cases, trying to flow fluid into a tank that can't accept them (because it's full or has a different fluid, etc.) will still cause updates - this will be fixed

**Comment by bdew** [comment]
Oh and about tanks from other mods not causing chunk updates - this is down to how rendering is handled. Some mods use Tile Entity rendering - those will not show up in chunk updates but have to run every frame. My mods use ISimpleBlockRenderingHandler which only runs when an update happens with minecraft saving and reusing the rendered geometry of the whole chunk.

**Comment by Caldurin** [comment]
Ah, that's interesting to know, thanks. Also, regarding inserting fluid into tanks that are full - that might explain some of the behaviour I saw initially.
Anyhow, I appreciate the responses!
