### ISSUE TITLE
Suggestion: Way to Upgrade Tank Capacity / Smart Outlet

### ISSUE THREAD

**Issue by Skar78** [bdew-minecraft/pressure#39]
I think the Tank multiblock could use some improvements.

Currently the limited capacity (32x50=1600 buckets) seem to make it only interesting as storage as long as you can not hook up bedrock drums or similar.

After seeing the awesome idea of turbine upgrades for adv gen I think something similar could be applied to the tank blocks to increase capacity.

Additionally a smart outlet that allows to configure the mb/t would make this a very useful buffer (for example for lava for maxed heat exchangers).

The line of thought here is to make the tank more useful as buffer, and while pure storage might be not the main motivation a more granular control about the consumption of its contents would probably be rewarding/useful.

As always, love the mods and keep up the great work!

**Comment by bdew** [comment]
Flow limiting is a good idea but i think it will make more sense as a standalone block or valve. I'll add that when i get to it.

Upgradeable tanks are planned.

**Comment by Skar78** [comment]
Hi,

The upgradeable capacity would still be very high on my wish list.

Thanks also to adv. generators you can just rush by that time a 1kk tank is exciting in a few hours.

I am looking now at the beautiful tanks and compare them to a bedrock drum and by this time i would not mind or care if they are made out of pure enderium if only they could match an bedrockium drum capacity with a block for block efficiency. 

Hell I wouldnt mind to need one bedrockium drum for each tank block to create something a kin to a DSU for liquid storage with reasonable space requirement.

 (Just hoping to move this feature up the list :))

**Comment by Utildayael** [comment]
Just checking in on this as it's about a year old or so now. Still on the to-do list @bdew?

While comparing to the insanely large Bedrockium Tanks in Extra Utils is a bit of a fools errand, it would be nice to see them grow a bit. I used to use these for gas storage for Mekanism v8 back in the day before Aidan implemented my suggestion to add "tiered" gas tanks with the top one holding 512,000mb [up from 96k iirc].

Did some more "sane" comparisons of what I'd call more equivalent items:

PP Tank: 5x5x5 - ~4,000,000 mb using only the essential tank controller and a fluid intake
Mekanism v9 Dynamic Tank: 5x5x5x - 20,000,000 mb
Railcraft Iron Tank: 5x5x5  2,000,000 mb
Railcraft Steel Tank: 5x5x5x  4,000,000 mb
Immersive Engineering Tank:  3x3x5  512,000 mb
Buildcraft Tank: 1 block - 16 buckets [ok had to throw that in for a joke]

So I guess it's really a wash. Railcraft isn't out for 1.10 so I pulled the 1.7 numbers. Extra Utils is both better and worse in 1.10 having tiered tanks and no bedrockium tank so max size EU tank is ~4M mb currently tho I know he has the bigger ones "in the works" ... I don't really compare them to PP/Mek/RC/IE tanks tho because they are "magic blocks" that hold a ton of liquid in a single block. The EU drums are scaled so poorly it makes all multiblock tanks look terrible by comparison.

I think a good target for tiering would be to at least match the Mekanism dynamic tanks which have you beat out by a factor of 5x granted in both cases there is only one tier and the PP ones drop capacity with extra "utility" blocks added in whereas the Mek ones do not. Of course the Mek ones also have very specific build rules as they are required to be cuboid and the outside frame must be the solid blocks tho you can use the structural glass for the "side panels" which makes them prettier to look it. [I'd love to see that with your tanks as well, somehow, but I know that is a bit harder since your build rules for tanks are really damn near any shape you want, window blocks that connect to eachother to make bigger, uh, windows perhaps?]

Tier-wise... I guess it depends how crazy you want to go. If you want to be the "go to" fluid storage mod, you really just have to make your top tier > Mek's dynamic tanks and ignore Extra Utils since it isn't comparable really. I can't see any scenario where you would want to make your tanks so nuts that a single block holds 4M+ mb but I could be wrong and would wholly welcome such a thing as I love to store tons of fluids and whatnot "just because" ... :)

Sorry bit long winded but love Pressure Pipes and constantly looking for new ways to use it in my builds. :)

Cheers!

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
