### ISSUE TITLE
Tank Controller - Causes Major Lag

### ISSUE THREAD

**Issue by chloeprince** [bdew-minecraft/pressure#48]
Hey Bdew,

I love the Pressure pipes mod, but one thing that has a major impact on the ability to add a few of your tanks into a world, is the major source of lag that the controller block causes. If you put one or 2 down, your fine, but start building more than than on a server, and its a big problem. Can you work to increase the performance of the controller block so they are not so laggy?

Take a look at my OPIS screen shot of my server - this is on a GOOD day too, and I only have 3 tanks in the world. These tanks can actually kill a server if to many are built.

![screen shot 2015-07-27 at 7 05 38 pm](https://cloud.githubusercontent.com/assets/6889524/8920072/fc1a64ea-3492-11e5-85db-dbfd3d33962b.png)

**Comment by bdew** [comment]
First of all, 70us is really not that much. Your total update is 1550us - which is 3.1% of the 50ms that a tick can take before you get TPS lag. And 76us is ~5% of those 3.1%. And that is with profiling overhead from WAILA which makes everything slower.

Also note that the tick time for the controller includes the time it takes for all active outputs and whatever they are pushing into. If they are pushing into something with instant transfer (e.g. pressure pipe network) - this also includes the time for whatever that outputs into to handle the fluid.

Depending on the setup that can include a very significant time spent in code outside my control that WAILA attributes to the controller.

I'll look into improving performance, but i'm not sure if there's much room for improvement there.

One thing i could do is add a serverwide option to throttle down output, so that tanks output once in X ticks instead of every tick, but this could break builds that don't have sufficient buffering.

**Comment by chezpaul** [comment]
I have also noticed lag on my server when I'm int he same room as 2 tank of yours. On a side note, anything on that tank flickers. The main blocks flicker, the controller flickers, the level block flickers, it all flickers. MY fps goes down to 11. If I break the two tanks, it goes back up to 60 fps.
No other block on my world flickers. Only the tank blocks. The pressure pipes don't flicker either.

Wherever I build a tank it will flickers. By flicker I mean to say that the blocks keep changing their skin.
then go back to what they are, then flicker.
All functions seem to work fine.

Def lag here. But love the mod.

I'm running 1.2.4.124 on KCauldron 1517.168

**Comment by chloeprince** [comment]
Are you using opti fine? I've see this glitch with that mod installed.

**Comment by bdew** [comment]
Does the flicker affect the borders or the whole block?

I've seen an issue with the borders flickering with optifine on some GPUs - never managed to figure out  how to fix this.

At any rate this is unrelated to the original issue of tickrate lag - which i haven't forgot about and still plan to address when i'm a bit less overloaded with RL stuff and other projects, sorry @chloeprince.

**Comment by chezpaul** [comment]
Indeed, without Optifine the flickers go away but my FPS drops from 60 to 20, playable but not as satisfying on the mind.  ;-)

Chloe, I'm a big fan of your youtube video's, you taught me a lot. Thanks.
Keep em coming. BTW, you are years ahead of anyone else when it comes to engineering the shit out of something and making it look good.

I've always thought of Optifine as the number 1 mod to install and have never understood why some moders don't try to make it work with their mod. But I'm not a modder. So I'll shut up.  ;-)

**Comment by chezpaul** [comment]
By the way, Chloé, your custom.cfg little tweak doesn't work for me. Should I be declaring custom.cfg in another file as it doesn't exist at first?

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
