### ISSUE TITLE
Change tank capacity limit.

### ISSUE THREAD

**Issue by OneEyeMaker** [bdew-minecraft/pressure#54]
Hello.
I found one simple problem: tank capacity limit is too low.
For example, I want to transform Tank Multiblock to the hugest liquid storage on my modpack. And for that purpose I set capacity of single Tank block equals capacity of bedrockium drum from ExtraUtilities (also, I changed recipe accordingly).  But when I try to build this multiblock with these settings, I get Tank with negative capacity (with low value about -2 millions = ).

As I understand, this is because you use `int` type for capacity variable. Please, fix it:
- Change type to `long`, for example (and I understand, that it'll greatly increase load and network traffic);
- or set the maximum allowable value for Tank capacity.

P. S. Sorry for my English, I'm from Russia.

**Comment by bdew** [comment]
Changing to long isn't really an option because forge uses int for everything related to fluids, and it causes all kinds of weird issues when your tank contains more than forge can handle.

Also i really doubt there is a real sane reason to store more than 2^31 milibuckets of anything.

I'll add a warning and maybe cap the value to something saner when the configs are loaded.

**Comment by OneEyeMaker** [comment]
Thank you very much!

**Comment by bdew** [comment]
I'll close this when it's done

**Comment by Unrepentant-Atheist** [comment]
Why would forge use int over unsigned int for fluids? It doesn't make any sense to have negative integers for fluids...

**Comment by bdew** [comment]
There are no primitive unsigned types in java :P

And the "why not long" is probably because it was inherited from BC fluid system and "2^31-1 millibucket ought to be enough for anybody"
