### ISSUE TITLE
BlockTankIndicator randomly causes java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by redpandaka** [bdew-minecraft/pressure#62]
Can't really say when it happens or how to reproduce it, but our server occasionally crashes with the exception/error mentioned above. For more details check the attached crash report.

[crash-2016-03-05_20.57.49-server.txt](https://github.com/bdew/pressure/files/160087/crash-2016-03-05_20.57.49-server.txt)

**Comment by bdew** [comment]
That was a fun one. The crash happened when the server checked if a mob could spawn on top of a tank indicator block. That check would call Block.isSideSolid, which calls getActualState for no reason (it doesn't do anything with the result for normal blocks), which would try to access stuff that's not available on servers and caused the crash. 

Should be fixed in this build - http://minecraft.curseforge.com/projects/pressure-pipes/files/2285631

**Comment by redpandaka** [comment]
I'll be playing again later today for a longer period of time, I'll re-install my Tank Indicator setup and give you feedback by tomorrow if it still crashes! Thanks!
